'use strict';
const express=require('express');
const multer=require('multer');
const crypto=require('node:crypto');
const {requireAuth,ensureCsrf,verifyCsrf,safeEqual}=require('../middleware/security');
const {escapeHtml,layout}=require('../utilities/html');
const {maskCode}=require('../utilities/mask');
const {importCsv}=require('../services/csv-importer');
function table(headers,rows){return `<div class="table-wrap"><table><thead><tr>${headers.map(h=>`<th>${escapeHtml(h)}</th>`).join('')}</tr></thead><tbody>${rows.join('')||`<tr><td colspan="${headers.length}">No records</td></tr>`}</tbody></table></div>`;}
function createDashboardRouter({pool,config}){
 const router=express.Router();
 const upload=multer({storage:multer.memoryStorage(),limits:{fileSize:config.maxCsvSizeMb*1024*1024,files:1},fileFilter:(_r,f,cb)=>cb(null,f.mimetype==='text/csv'||/\.csv$/i.test(f.originalname))});
 router.use(ensureCsrf);
 router.get('/login',(req,res)=>res.send(layout('Login',`<section class="card narrow"><h1>Administrator login</h1><form method="post" action="/login"><input type="hidden" name="_csrf" value="${req.session.csrfToken}"><label>Username<input name="username" required autocomplete="username"></label><label>Password<input type="password" name="password" required autocomplete="current-password"></label><button>Log in</button></form></section>`)));
 router.post('/login',verifyCsrf,(req,res)=>{if(safeEqual(req.body.username,config.adminUsername)&&safeEqual(req.body.password,config.adminPassword)){req.session.regenerate(e=>{if(e)return res.status(500).send('Login failed');req.session.authenticated=true;req.session.csrfToken=crypto.randomBytes(32).toString('hex');res.redirect('/dashboard');});}else res.status(401).send(layout('Login','<section class="card narrow"><h1>Login failed</h1><a href="/login">Try again</a></section>'));});
 router.post('/logout',requireAuth,verifyCsrf,(req,res)=>req.session.destroy(()=>res.redirect('/login')));
 router.use('/dashboard',requireAuth);
 router.get('/dashboard',async(req,res,next)=>{try{const result=await pool.query(`SELECT cc.category,count(c.id) FILTER (WHERE c.status='unused')::int unused,count(c.id) FILTER (WHERE c.status='used')::int used,count(c.id) FILTER (WHERE c.delivery_status='failed')::int failed FROM code_categories cc LEFT JOIN codes c ON c.category=cc.category WHERE cc.active=TRUE GROUP BY cc.category ORDER BY cc.category`);const rows=result.rows.map(r=>`<tr><td>${escapeHtml(r.category)}</td><td>${r.unused}</td><td>${r.used}</td><td>${r.failed}</td></tr>`);res.send(layout('Inventory',`<h1>Inventory</h1>${table(['Category','Unused','Used','Failed delivery'],rows)}<section class="card"><h2>Import CSV</h2><form method="post" action="/dashboard/import" enctype="multipart/form-data"><input type="hidden" name="_csrf" value="${req.session.csrfToken}"><input type="file" name="csv" accept=".csv,text/csv" required><button>Import</button><small>Maximum ${config.maxCsvSizeMb} MB. Codes are never displayed here.</small></form></section>`,req.session.csrfToken));}catch(e){next(e);}});
 router.post('/dashboard/import',upload.single('csv'),verifyCsrf,async(req,res,next)=>{try{if(!req.file)return res.status(400).send('A valid CSV file is required');const r=await importCsv(pool,req.file.buffer.toString('utf8'));res.send(layout('Import result',`<section class="card"><h1>Import complete</h1><p>Imported: ${r.imported} &middot; Skipped: ${r.skipped} &middot; Failed: ${r.failed}</p><a href="/dashboard">Return</a></section>`,req.session.csrfToken));}catch(e){next(e);}});
 router.get('/dashboard/groups',async(req,res,next)=>{try{const groups=(await pool.query('SELECT * FROM allowed_groups ORDER BY group_name')).rows;const rows=groups.map(g=>`<tr><td>${escapeHtml(g.group_name)}</td><td><code>${escapeHtml(g.group_id)}</code></td><td>${g.active?'Active':'Disabled'}</td><td><form method="post" action="/dashboard/groups/toggle"><input type="hidden" name="_csrf" value="${req.session.csrfToken}"><input type="hidden" name="group_id" value="${escapeHtml(g.group_id)}"><input type="hidden" name="active" value="${g.active?'false':'true'}"><button>${g.active?'Disable':'Enable'}</button></form></td></tr>`);res.send(layout('Groups',`<h1>Authorized groups</h1>${table(['Name','Group ID','Status','Action'],rows)}`,req.session.csrfToken));}catch(e){next(e);}});
 router.post('/dashboard/groups/toggle',verifyCsrf,async(req,res,next)=>{try{await pool.query('UPDATE allowed_groups SET active=$2,updated_at=NOW() WHERE group_id=$1',[req.body.group_id,req.body.active==='true']);res.redirect('/dashboard/groups');}catch(e){next(e);}});
 router.get('/dashboard/audit',async(req,res,next)=>{try{const where=[];const values=[];for(const [key,col] of [['category','a.category'],['group','a.group_id']])if(req.query[key]){values.push(req.query[key]);where.push(`${col}=$${values.length}`);}if(req.query.date){values.push(req.query.date);where.push(`a.created_at >= $${values.length}::date AND a.created_at < $${values.length}::date + interval '1 day'`);}const records=(await pool.query(`SELECT a.*,c.code FROM audit_logs a LEFT JOIN codes c ON c.id=a.code_id ${where.length?`WHERE ${where.join(' AND ')}`:''} ORDER BY a.created_at DESC LIMIT 500`,values)).rows;const rows=records.map(a=>`<tr><td>${escapeHtml(a.created_at.toISOString())}</td><td>${escapeHtml(a.action)}</td><td>${escapeHtml(a.category)}</td><td>${escapeHtml(a.group_id)}</td><td>${escapeHtml(maskCode(a.code))}</td><td>${escapeHtml(a.delivery_status)}</td><td>${escapeHtml(a.error_message)}</td></tr>`);const filters=`<form class="filters"><input name="category" placeholder="Category" value="${escapeHtml(req.query.category)}"><input name="group" placeholder="Group ID" value="${escapeHtml(req.query.group)}"><input type="date" name="date" value="${escapeHtml(req.query.date)}"><button>Filter</button></form>`;res.send(layout('Audit',`<h1>Audit history</h1>${filters}${table(['UTC time','Action','Category','Group','Code','Delivery','Error'],rows)}`,req.session.csrfToken));}catch(e){next(e);}});
 router.get('/dashboard/failed',async(req,res,next)=>{try{const records=(await pool.query("SELECT id,category,code,used_by_group,requested_by,used_at FROM codes WHERE delivery_status='failed' ORDER BY used_at DESC")).rows;const rows=records.map(c=>`<tr><td>${c.id}</td><td>${escapeHtml(c.category)}</td><td>${escapeHtml(maskCode(c.code))}</td><td>${escapeHtml(c.used_by_group)}</td><td>${escapeHtml(c.requested_by)}</td><td>${escapeHtml(c.used_at?.toISOString())}</td></tr>`);res.send(layout('Failed deliveries',`<h1>Failed deliveries</h1><p>Review manually. Codes remain used.</p>${table(['Reference','Category','Masked code','Group','Requester','UTC time'],rows)}`,req.session.csrfToken));}catch(e){next(e);}});
 return router;
}
module.exports={createDashboardRouter};
